{
 "title": "latest_Dashboard",
 "description": "Smart-City",
 "time": { "from": "2025-01-12T14:55:30.525Z", "to": "2025-01-12T15:09:17.437Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hbf_westbf",
    "label": "Lichtschranke zur Erkennung der Bahn",
    "query": "SELECT\n  CASE \n    WHEN id = 3210 THEN 'Westbahnhof'\n    WHEN id = 3220 THEN 'Westbahnhof'\n    WHEN id = 2210 THEN 'Hauptbahnhof'\n    WHEN id = 2220 THEN 'Hauptbahnhof'\n    ELSE 'Unknown'\n  END AS text,\n  id AS value\nFROM light_sensor\n\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Freie Parkplätze",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH last_packet AS (\r\n    SELECT *\r\n    FROM light_park_sensor\r\n    ORDER BY timestamp DESC\r\n    LIMIT 3\r\n)\r\nSELECT\r\n    COUNT(*) AS Freie_Plätze\r\nFROM last_packet\r\nWHERE value = 0;\r\n"
    }
   ]
  },
  {
   "title": "Umwelt",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Gas\" FROM gas_sensor LIMIT 50 "
    },
    {
     "rawSql": "SELECT value AS \"Feuchtigkeit\" FROM feuchtigkeit_sensor LIMIT 50 "
    },
    {
     "rawSql": "SELECT value AS \"Luftdruck\" FROM luftdruck_sensor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM temperatur_sensor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Umwelt",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Temperatur\", \"timestamp\" FROM temperatur_sensor ORDER BY timestamp DESC\r\nLIMIT 1000"
    },
    {
     "rawSql": "SELECT value AS \"Gas\", \"timestamp\" FROM gas_sensor ORDER BY timestamp DESC\r\nLIMIT 1000"
    },
    {
     "rawSql": "SELECT value AS \"Luftdruck\", \"timestamp\" FROM luftdruck_sensor ORDER BY timestamp DESC\r\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Ampelswitch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\", \"timestamp\" FROM rfid_sensor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Ampelswitch ",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\", \"timestamp\" FROM rfid_sensor ORDER BY timestamp DESC\r\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Autozähler",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM park_zahler_sensor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Lichtintensität",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\", \"timestamp\" FROM light_intens_sensor ORDER BY timestamp DESC\r\nLIMIT 1000 "
    }
   ]
  },
  {
   "title": "Buserkennung",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\", \"timestamp\" FROM rfid_bus_sensor WHERE value=true ORDER BY timestamp DESC\r\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Bahnerkennung",
   "type": "table",
   "description": "Lichtschranke",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"Ort\", value AS \"Zustand\", \"timestamp\" FROM light_sensor ORDER BY timestamp DESC\r\nLIMIT 1000"
    }
   ]
  }
 ]
}