{
 "title": "Smart-City",
 "time": { "from": "2024-12-08T10:52:53.436Z", "to": "2024-12-08T10:55:44.908Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "id", "label": "RFID ", "query": "select id from RFID_sensor" },
   { "name": "parkplatz", "label": "Bewegungsensor", "query": "select id from motion_sensor" },
   { "name": "lightsensor_id", "label": "Lichtschranke", "query": "select id from light_sensor" }
  ]
 },
 "panels": [
  {
   "title": "Time-Series-Lärm",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT value, \"time\" FROM noise_sensor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Lärm",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM noise_sensor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Umwelt",
   "type": "table",
   "description": "110: Temperatur, 111: Gas, 112 Feuchtigkeit, 113: Luftdruck",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Feuchtigkeit\", \"time\" FROM feuchtigkeit_sensor LIMIT 50 "
    },
    {
     "rawSql": "SELECT value AS \"Luftdruck\", \"time\" FROM luftdruck_sensor LIMIT 50 "
    },
    {
     "rawSql": "SELECT value AS \"Temperatur\", \"time\" FROM temperatur_sensor LIMIT 50 "
    },
    {
     "rawSql": "SELECT value AS \"Gas\", \"time\" FROM gas_sensor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Umwelt",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Temperatur\", \"time\" FROM temperatur_sensor LIMIT 50 "
    },
    {
     "rawSql": "SELECT value AS \"Gas\", \"time\" FROM gas_sensor LIMIT 50 "
    },
    {
     "rawSql": "SELECT value AS \"Feuchtigkeit\", \"time\" FROM feuchtigkeit_sensor LIMIT 50 "
    },
    {
     "rawSql": "SELECT value AS \"Luftdruck\", \"time\" FROM luftdruck_sensor LIMIT 50 "
    }
   ]
  },
  {
   "title": "RFID",
   "type": "table",
   "description": "120: Westbahnhof, 121: HBH, 122: Kreuzung",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"Ort\", value AS \"Zustand\", time AS \"Zeit\"  FROM rfid_sensor WHERE id IN (${id:csv}) LIMIT 1000"
    }
   ]
  },
  {
   "title": "Parkplatz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(value) FROM light_sensor WHERE id IN (${lightsensor_id:csv}) LIMIT 100 "
    }
   ]
  },
  {
   "title": "Lichtschranke",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"Ort\", value AS \"Zustand\", \"time\" AS \"Zeit\" FROM light_sensor WHERE id IN (${lightsensor_id:csv}) LIMIT 50 "
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM light_sensor WHERE id IN (${lightsensor_id:csv}) LIMIT 100"
    }
   ]
  },
  {
   "title": "Time-Series-RFID",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT * FROM rfid_sensor WHERE id IN (${id:csv}) LIMIT 1000"
    }
   ]
  },
  {
   "title": "Bewegungsensor",
   "type": "table",
   "description": "140: West, 141: HBH",
   "gridPos": { "h": 5, "w": 11, "x": 10, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"Ort\", value AS \"Geschwindigkeit\", \"time\" AS \"Zeit\" FROM motion_sensor WHERE id IN (${parkplatz:csv})  LIMIT 50 "
    }
   ]
  },
  {
   "title": "Geschwindigkeit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM motion_sensor WHERE id IN (${parkplatz:csv}) LIMIT 50 "
    }
   ]
  }
 ]
}