{
 "title": "Stadt_dashboard",
 "description": "Smart-City",
 "time": { "from": "2025-01-12T14:34:50.157Z", "to": "2025-01-12T15:29:57.805Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "light_sensor",
    "label": "Bahnerkennung",
    "query": "SELECT\n  CASE \n    WHEN id = 2210 THEN 'Hauptbahnhof'\n    WHEN id = 2220 THEN 'Hauptbahnhof'\n    WHEN id = 3210 THEN 'Westbahnhof'\n    WHEN id = 3220 THEN 'Westbahnhof'\n  END AS __text,\n  id AS __value\nFROM light_sensor"
   }
  ]
 },
 "panels": [
  {
   "title": "Freie Parkplätze",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH last_packet AS (\r\n    SELECT *\r\n    FROM light_park_sensor\r\n    ORDER BY timestamp DESC\r\n    LIMIT 3\r\n)\r\nSELECT\r\n    COUNT(*) AS Freie_Plätze\r\nFROM last_packet\r\nWHERE value = 0;\r\n"
    }
   ]
  },
  {
   "title": "Temperatur °C",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM temperatur_sensor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Gas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM gas_sensor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Feuchtigkeit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM feuchtigkeit_sensor ORDER BY \"timestamp\" DESC LIMIT 2 "
    }
   ]
  },
  {
   "title": "Umwelt",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Temperatur\", \"timestamp\" FROM temperatur_sensor ORDER BY timestamp DESC\r\nLIMIT 1000"
    },
    {
     "rawSql": "SELECT value AS \"Gas\", \"timestamp\" FROM gas_sensor ORDER BY timestamp DESC\r\nLIMIT 1000"
    },
    {
     "rawSql": "SELECT value AS \"Feuchtigkeit\", \"timestamp\" FROM feuchtigkeit_sensor ORDER BY timestamp DESC\r\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Bus Haltstelle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\" FROM rfid_bus_sensor ORDER BY \"timestamp\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Bahnhof",
   "type": "stat",
   "description": "Lichtschranke",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT id AS \"Ort\", value AS \"Zustand\", \"timestamp\" FROM light_sensor WHERE id IN (${light_sensor:csv} ) ORDER BY \"timestamp\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Lichtintensität",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\" FROM light_intens_sensor ORDER BY \"timestamp\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Autozähler",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM park_zahler_sensor ORDER BY \"timestamp\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Ampelswitch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\", \"timestamp\" FROM rfid_sensor ORDER BY \"timestamp\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Ampelswitch ",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\", \"timestamp\" FROM rfid_sensor ORDER BY timestamp DESC\r\nLIMIT 1000"
    }
   ]
  }
 ]
}