{
 "title": "Smart-City-Test-File-JSON",
 "description": "Smart-City",
 "time": { "from": "2025-01-12T14:34:50.157Z", "to": "2025-01-12T15:29:57.805Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Freie Parkplätze",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH last_packet AS (\r\n    SELECT *\r\n    FROM light_park_sensor\r\n    ORDER BY timestamp DESC\r\n    LIMIT 3\r\n)\r\nSELECT\r\n    COUNT(*) AS Freie_Plätze\r\nFROM last_packet\r\nWHERE value = 0;\r\n"
    }
   ]
  },
  {
   "title": "Temperatur °C",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM temperatur_sensor ORDER BY \"timestamp\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Gas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM gas_sensor ORDER BY \"timestamp\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Feuchtigkeit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM feuchtigkeit_sensor ORDER BY \"timestamp\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Ampelswitch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\", \"timestamp\" FROM rfid_sensor ORDER BY \"timestamp\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Westbahnhof",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\", id AS \"Haltstelle\" FROM light_sensor_west ORDER BY \"timestamp\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Bus Haltstelle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\" FROM rfid_bus_sensor ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Hauptbahnhof",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\", id AS \"Haltstelle\" FROM light_sensor_hbf ORDER BY \"timestamp\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Autozähler",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM park_zahler_sensor "
    }
   ]
  },
  {
   "title": "Lichtintensität",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"Zustand\" FROM light_intens_sensor ORDER BY \"timestamp\" DESC LIMIT 1 "
    }
   ]
  }
 ]
}